module.exports = {
  USER_CREATED_SUCCESS: 'USER_CREATED_SUCCESS',
  USER_UPDATED_SUCCESS: 'USER_UPDATED_SUCCESS',

  SHORTNER_CREATED_SUCCESS: 'SHORTNER_CREATED_SUCCESS',
  SHORTNER_UPDATED_SUCCESS: 'SHORTNER_UPDATED_SUCCESS',
  SHORTNER_DELETED_SUCCESS: 'SHORTNER_DELETED_SUCCESS',
}